### ISSUE TITLE
Question: how to benchmark the real-world apps

### ISSUE THREAD

**Issue by ustiugov** [SJTU-IPADS/ServerlessBench#13]
Dear maintainers,

I was unable to find the code and the instructions to deploy and benchmark the real-world apps: images processing, Alexa skill, data analysis.

Could you please help me with that?

**Comment by CodingYuanLiu** [comment]
Hello, thanks for your issue and sorry for the delay.

You can use `deploy.sh` and `eval.sh` to deploy and evaluate the apps separately. Before that, you need to copy `template.local.env` to `local.env` and fill in configuration file's blanks.

Don't forget to set the environment variable: `export TESTCASE4_HOME=$WHERE_YOUR_SERVERLESSBENCH_IS/Testcase4-Application-breakdown`. This will help crucial scripts to find the helper scripts.

By the way, other scripts in the /scripts subdirectory of every app may be helpful for you.

If there's any problem, please contact us

**Comment by ustiugov** [comment]
thanks a lot!
