### ISSUE TITLE
Benchmarking Composer 

### ISSUE THREAD

**Issue by Giannos-G** [SJTU-IPADS/ServerlessBench#15]
Hello,

I am using Openwhisk Composer (on k3s) and I would like to benchmark my cluster in terms of latency and throughput. I used some of the testcases to benchmark Openwhisk, could you give me some advice on how to modify these testcases so that they can run on the composer too?

Thank you!

**Comment by Ddnirvana** [comment]
Hi,
    Sorry for my late response.
    We do not run our benchmarks on composer with k3s yet.
    Although composer shares the same client interfaces as OpenWhisk, it seems they have different programming models, e.g., define functions in composer.action.
    I suggest that you pick simple cases in serverlessBench and try to manually port them to composer first, and try application cases when you are familiar with the porting things.

All the best,
Dong

**Comment by Giannos-G** [comment]
Thank you very much I will try that!
