### ISSUE TITLE
TestCase11

### ISSUE THREAD

**Issue by hsiehkaofeng** [SJTU-IPADS/ServerlessBench#17]
Hello,
According to TestCase11 on the paper, you used MemBandwidth application as a memory intensive workload. However, TestCase11 on Github seems not the same as TestCase11 on the paper. I'm wondering if the MemBandwidth application mentioned on the paper exists inside TestCase11 on Github (like function.c) ?

**Comment by CodingYuanLiu** [comment]
Hello,
We do not open source TestCase11 and TestCase12 mentioned in the SoCC paper, as they are evaluated on a private cloud (Ant Financial).
The Testcase11 on Github now is a new one, not mentioned in the paper.

**Comment by hsiehkaofeng** [comment]
Thanks for the info.
