### ISSUE TITLE
[TestCase4] Problem with Source Code of Image-Processing functions.

### ISSUE THREAD

**Issue by adhinneupane** [SJTU-IPADS/ServerlessBench#19]
Hi, The image used to execute the Testcase4/ functions is dplsming/java8action-imagemagic 

The functions cannot run in the this container with the following error

```
Cannot pull dplsming/java8action-imagemagic container doesn't exist 
```

I tried to execute it in a different container with java8action and imagemagic installed but there seems to be other factors included in the missing docker image on which the function execution relies. 

with barebone java8action-imagemagic, docker image
```
 Generates NullPointerException
```

Could you please check your docker hub account and add the aforementioned image? Would appreciate other suggested workarounds for the same as well.

**Comment by adhinneupane** [comment]
@CodingYuanLiu

**Comment by adhinneupane** [comment]
@Ddnirvana

**Comment by CodingYuanLiu** [comment]
Thanks for your question. Try it now please.

**Comment by adhinneupane** [comment]
Hi YuanLiu, thank you for taking time to reply. I still do not see the docker container under your dplsming/ dockerhub profile. Can you please check whether you have made it public or let us know the dependencies that have been installed in that image.

**Comment by CodingYuanLiu** [comment]
Sorry, but I can pull `dplsming/java8action-imagemagic` successfully.

**Comment by adhinneupane** [comment]
@CodingYuanLiu Thanks for making the container public. I was able to run it. 
I am still getting issues with execution of some functions with this message in openwhisk logs. could this be a issue with the source code of the functions? 
I am using the container dplsming/java8action-imagemagic for execution. 

![image](https://user-images.githubusercontent.com/38281651/160309269-e5079519-2dec-4aba-b9e0-6c1717c02bc7.png)

**Comment by adhinneupane** [comment]
Also, could you please add some comments to the local.env.template ? For someone just trying out these tools for first time it would be helpful.

**Comment by CodingYuanLiu** [comment]
Thank you for your reply. The error could happen because of any reason. For example, you may write a wrong couchdb ip/port in local.env. You may access the error logs and find the reason.

**Comment by adhinneupane** [comment]
I understand that it could be a configuration issue with my setup. I have double checked it to ensure that it is able to connect to all its dependencies. 
Also attaching a screenshot for successful deployment of functions for imageprocessing

![image](https://user-images.githubusercontent.com/38281651/160904609-4a0fad5e-e832-47c0-ac59-29776cd76099.png)

As the benchmark is able to upload images and functions to openwhisk, couchdb,  the only problem I am having is when the functions have to be invoked by themselves. 

I am running openwhisk in standalone mode with standalone Boot Run:

![image](https://user-images.githubusercontent.com/38281651/160904961-65dfcd6a-dbfa-4901-a43c-a8ef4e6842dd.png)

Do i need to setup openwhisk with specific configs of couchdb and not in the standalone mode?  



.

**Comment by adhinneupane** [comment]
I enabled openwhisk with customconfigs for couchdb connections. That too doesn't seem to work. 

This is the error from openwhisk logs and function invocations respetively. 

![image](https://user-images.githubusercontent.com/38281651/160911408-d30c43f9-506e-4e2a-bd7c-44075ca1f84c.png)
![image](https://user-images.githubusercontent.com/38281651/160911560-ea325ec1-10d1-4a81-aaa8-81932e9f0d1c.png)

**Comment by CodingYuanLiu** [comment]
Thanks for your reply. I can use openwhisk-docker-compose and openwhisk with kubernetes to run the benchmark successfully. Your information is not enough for me to identify the error. Maybe using `wsk logs <activation-id>` could help you.

**Comment by adhinneupane** [comment]
HI @CodingYuanLiu 
Although I should have said this probably earlier but the issue I am having is with
With TestCase4 - imageprocessing workload (even the other workloads online compiling , e.t.c work fine) 

After checking my local.env and making sure all dependency endpoints/ports/resources are available, I tried to rerun it with the same error Java NULL Pointer exception. 

I went a bit deeper and checked the wsk logs which show that only some functions ```transformImageData``` and ```imageProcessSequence``` do not run with error: Developer error as seen in wsk logs. 

![image](https://user-images.githubusercontent.com/38281651/163012666-0ffe7cf7-79ed-42f8-84cd-723448ab58e6.png)

I checked docker containers to see if all of them have started too to ensure that no request times out. 
I made sure the config (wsk, local.env) is correct (thus the uploads and deploy.sh, invocations is successfull) 

I also switched to a higher Computer machine to ensure openwhisks own docker containers have plenty of resource capacity to not delay any requests. 

Can you help me check whether this image processing workload benchmark is working?

**Comment by CodingYuanLiu** [comment]
Could you provide some information from `wsk activation logs <id>` to see what happened to cause the error? I have no idea how you config your openwhisk and how your local.env is written, and where does the Null pointer exception come from.
I guess maybe your `extractImageMetadata` fail to access the couchdb so that the `transformMetadata` can not get the corresponding argument from `extractImageMetadata`'s output.

**Comment by adhinneupane** [comment]
Hi @CodingYuanLiu 

Here are the wsk logs 
![image](https://user-images.githubusercontent.com/38281651/164298300-c820c5fb-0d6c-4ad2-ad07-9d1972c1c029.png)

Here is the local.env (this is not incorrect - else the functions /database deployments) would not be deployed successfully. Still posting it here for your reference.

```
# Openwhisk
OPENWHISK_APIHOST=172.17.0.1
OPENWHISK_APIPORT=3232
OPENWHISK_TOKEN='N/A'

# CouchDB
COUCHDB_IP=127.0.0.1
COUCHDB_PORT=5984
COUCHDB_USERNAME="admin"
COUCHDB_PASSWORD="mypassword"

# image-processing
IMAGE_DATABASE="images"
IMAGE_DATABASE_LOG="image-logs"

# alexax
# smarthome parameters
ALEXA_SMARTHOME_IP=
ALEXA_SMARTHOME_PORT_DOOR=1000
ALEXA_SMARTHOME_PORT_LIGHT=1001
ALEXA_SMARTHOME_PORT_TV=1002
ALEXA_SMARTHOME_PORT_AIR_CONDITIONING=1003
ALEXA_SMARTHOME_PORT_PLUG=1004
ALEXA_SMARTHOME_PASSWORD="Taylor Swift"
# reminder parameters
ALEXA_REMINDER_COUCHDB_DATABASE="reminder"

# online-compiling
GG_MODELPATH=
GG_STORAGE_URI=

# data-analysis
WAGE_COUCHDB_INSTANCE="openwhisk-couchdb"
WAGE_COUCHDB_DATABASE="wage"
WAGE_COUCHDB_DATABASE_STATISTICS="wage-statistics"

# data analysis couchdb package provider
COUCHDB_PROVIDER_PORT=5984
COUCHDB_PROVIDER_PROTOCOL=chttpd
COUCHDB_PROVIDER_DB_PREFIX=prefixforvirtualhost
COUCHDB_PROVIDER_ROUTER_HOST=127.0.0.2
COUCHDB_PROVIDER_DATABASE_TRIGGER=couchdbtrigger
```
As for the Null pointer exception, it can be only generated from the source file of these functions. 


I had  hoped for this benchmark to be used as part of my research and cited but my deadlines are being setback due to these errors. 

Would really appreciate it if these were looked at. A duplicate issue has been opened for the same by another user.

**Comment by QWQyyy** [comment]
very interesting

**Comment by CodingYuanLiu** [comment]
Hi [adhinneupane](https://github.com/adhinneupane).
I mean `wsk log` is not the activation list that you demonstrate here. I mean the actual log from the specific function instance. That can help you and me to understand where the Error comes from.
For example. You can use `wsk activation logs abe98dcb7ca647dfa98dcb7ca6a7dfb2` to see the error log from your `transformMetadata` function.

**Comment by adhinneupane** [comment]
The function invocations are successfull. 

![image](https://user-images.githubusercontent.com/38281651/164745570-4e54c4c1-a134-4420-b917-1fbd81a04f44.png)

Standalone Openwhisk is not giving me activation id's for failures: 
I need to use standalone with couchdb for my use case.

![image](https://user-images.githubusercontent.com/38281651/164745708-6f6cc9c1-35a8-4759-8dac-98dd10dec333.png)
 
 I was using openwhisk-dev-tools/docker-compose to run it when i got the devloper error logs as seen in previous comments. 
 
 @CodingYuanLiu  Are you able to run image-processing workload specifically or other test-cases? Can you please check on your end and let us know? If you are able to then I think we could benifit greatly if you share the configurations and dev-dependencies (if they are not documented)

**Comment by CodingYuanLiu** [comment]
@adhinneupane Let me show you the screenshots of image-processing running:
<img width="1256" alt="b8165031ebe55224deaf749ff6de711" src="https://user-images.githubusercontent.com/39847475/165345169-74585e61-4cb4-4e53-a74b-10d4085d85dd.png">
The activation logs can be seen below.
![538df5bf1c0f232877f95c01b1c8991](https://user-images.githubusercontent.com/39847475/165345446-e1f8bbb0-d56e-4f83-afeb-9f040b013954.jpg)
