### ISSUE TITLE
TestCase10 source code not have fn project, Only some wsk shell script.

### ISSUE THREAD

**Issue by QWQyyy** [SJTU-IPADS/ServerlessBench#21]
Sorry, I can't find the "TestCase10" test script of Fn project, Could you add it in your ServerlessBench project?
Thanks.

**Comment by CodingYuanLiu** [comment]
Thanks for your issue.
Sorry to say that we do not open source fn version of TC10. Actually it could be very easy to modify from openwhisk version to fn version.

**Comment by QWQyyy** [comment]
OK，thanks
