### ISSUE TITLE
是否支持测试弹性扩容？

### ISSUE THREAD

**Issue by ryuxin** [SJTU-IPADS/ServerlessBench#27]
弹性扩容是serverless的一个核心特性，请问当前benchmark是否支持？是否有相关文档？
多谢

**Comment by CodingYuanLiu** [comment]
弹性扩容通常是平台的特性，ServerlessBench主要针对OpenWhisk等开源平台，不对特定平台做操作。
如果要测试平台的弹性扩容性能，任意应用中包含的run.py可以并发发送请求，被测serverless系统在接收到并发请求后会弹性扩容，可以根据run.py返回的请求性能结果反映出弹性扩容的性能。

例如python-hello应用的run.py函数：https://github.com/SJTU-IPADS/ServerlessBench/blob/master/Testcase7-Sandbox-comparison/Python-hello/test/run.py
