### ISSUE TITLE
数据集失效

### ISSUE THREAD

**Issue by oreki-white** [SJTU-IPADS/ServerlessBench#28]
关于https://github.com/Azure/AzurePublicDataset/blob/master/AzureFunctionsDataset2019.md  中的 
  https://azurecloudpublicdataset2.z19.web.core.windows.net/azurepublicdatasetv2/azurefunctions_dataset2019/azurefunctions-dataset2019.tar.xz   的数据集失效了，无法下载

**Comment by CodingYuanLiu** [comment]
我们不负责维护这份数据集，这只能等他们恢复了。

**Comment by ActivePeter** [comment]
https://drive.google.com/file/d/1s_4lTpyryDF2CR1NQeeOESgmfbxJ_YVL/view?usp=sharing

We backed it up.
