### ISSUE TITLE
Any plan for Java test cases?

### ISSUE THREAD

**Issue by ziyilin** [SJTU-IPADS/ServerlessBench#4]
Do you have any plan to implement Java version test cases?

**Comment by Ddnirvana** [comment]
Hi @ziyilin ,
The major Java serverless application now is the Image-process case(https://github.com/SJTU-IPADS/ServerlessBench/tree/master/Testcase4-Application-breakdown/image-process).
As most other test cases are for evaluating serverless metrics that are irrelevant to the function languages, we do not have plan to support Java in those cases recently.

Could you describe more about the scenarios that you need java version test cases?
P.S., we welcome your contributions if you would like to add Java version support :)

**Comment by ziyilin** [comment]
I'm looking for a Java serverless benchmark suite for evaluating cloud services. It seems there is still no such a benchmark suite.
